### ISSUE TITLE
midi depricated

### ISSUE THREAD

**Issue by SArpnt** [Tumpnt/music-website#2]
should probably find up to date midi handler

**Comment by tumble1999** [comment]
if you're talking about this https://www.chromestatus.com/feature/5138066234671104 then that's talking specifically about the use of it on insecure origins

Github pages has an ssl [1]
we are fine


1. Github, _Securing your GitHub Pages site with HTTPS_ [online] Available at: https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https (Accessed 19/12/2019)
